FROM python:3.11-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /Web_Proyecto

# Copia solo requirements
COPY Web_Proyecto/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del proyecto
COPY Web_Proyecto/ .

CMD ["bash"]